## AIGCDetectBenchmark


In [ ]:
!git clone https://github.com/vohoaidanh/AIGCDetectBenchmark_ver2.git

In [ ]:
!pip install ftfy -q
!pip install natsort -q
!pip install blobfile -q
#!pip install mpi4py -q
!pip install comet_ml -q
!pip install grad-cam -q


In [ ]:
!pip install tensorboardX -q
!apt-get install -y unzip -q
!apt-get install -y zip -q
!pip install regex -q
!pip install imageio -q
!pip install opencv-python -q
!apt-get install -y libgl1-mesa-glx -q
!pip install scikit-learn -q
!pip install scikit-image -q
!pip install gdown -q
!pip install pickleshare -q

In [1]:
%cd /workspace/AIGCDetectBenchmark_ver2

/workspace/AIGCDetectBenchmark_ver2


In [47]:
!python siamese.py --method gen_feature

100%|███████████████████████████████████████| 3582/3582 [00:54<00:00, 66.09it/s]


In [ ]:
#Validation - Accuracy: 0.7440, Precision: 0.9218, Recall: 0.5298, F1-score: 0.6729 test with SiameseDatasetVal

In [29]:
import pickle
import numpy as np
# Define the path to your pickle file
feature_file = r'weights/RealFakeDB_train_feature.pkl'

# Open the pickle file in binary read mode and load its content
with open(feature_file, 'rb') as file:
    data = pickle.load(file)

pos_feature = data['pos_feature']
neg_feature = data['neg_feature']
X = np.concatenate((pos_feature, neg_feature), axis=0)

ones = np.ones(pos_feature.shape[0])
zeros = np.zeros(neg_feature.shape[0])
y = np.concatenate((ones, zeros))

print(f'shape X is {X.shape}, type X is {type(X)}')
print(f'shape y is {y.shape}, type y is {type(y)}')


shape X is (40000, 128), type X is <class 'numpy.ndarray'>
shape y is (40000,), type y is <class 'numpy.ndarray'>


In [31]:
!pip install pandas -q

In [51]:
#KNN model

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

k = 5  # Number of neighbors
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)



KNeighborsClassifier()

In [46]:
def predict(model, X, y):
    # Predict the labels for the test set
    y_pred = knn.predict(X)
    
    # Evaluate the model
    accuracy = accuracy_score(y, y_pred)
    print(f"Accuracy: {accuracy}")
    
    # Print classification report
    print("Classification Report:")
    print(classification_report(y, y_pred))
    
    # Print confusion matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y, y_pred))

predict(knn, X_test, y_test)

Accuracy: 0.922375
Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      0.89      0.92      3986
         1.0       0.90      0.95      0.93      4014

    accuracy                           0.92      8000
   macro avg       0.92      0.92      0.92      8000
weighted avg       0.92      0.92      0.92      8000

Confusion Matrix:
[[3548  438]
 [ 183 3831]]


## Eval


In [52]:
import pickle
import numpy as np
# Define the path to your pickle file
feature_file = r'weights/real_gen_dataset_train_feature.pkl'

# Open the pickle file in binary read mode and load its content
with open(feature_file, 'rb') as file:
    data = pickle.load(file)

pos_feature = data['pos_feature']
neg_feature = data['neg_feature']
X1 = np.concatenate((pos_feature, neg_feature), axis=0)

ones = np.ones(pos_feature.shape[0])
zeros = np.zeros(neg_feature.shape[0])
y1 = np.concatenate((ones, zeros))
X_test1, X_test2, y_test1, y_test2 = train_test_split(X1, y1, test_size=0.5, random_state=42)

print(f'shape X is {X1.shape}, type X is {type(X1)}')
print(f'shape y is {y1.shape}, type y is {type(y1)}')

# Standardize the features
X_test1 = scaler.transform(X_test1)
X_test2 = scaler.transform(X_test2)


shape X is (3582, 128), type X is <class 'numpy.ndarray'>
shape y is (3582,), type y is <class 'numpy.ndarray'>


In [53]:
predict(knn, X_test1, y_test1)

Accuracy: 0.5298715801228364
Classification Report:
              precision    recall  f1-score   support

         0.0       0.53      0.68      0.60       916
         1.0       0.53      0.37      0.43       875

    accuracy                           0.53      1791
   macro avg       0.53      0.53      0.52      1791
weighted avg       0.53      0.53      0.52      1791

Confusion Matrix:
[[625 291]
 [551 324]]


In [54]:
predict(knn, X_test2, y_test2)

Accuracy: 0.5371300949190396
Classification Report:
              precision    recall  f1-score   support

         0.0       0.52      0.71      0.60       874
         1.0       0.57      0.37      0.45       917

    accuracy                           0.54      1791
   macro avg       0.55      0.54      0.53      1791
weighted avg       0.55      0.54      0.52      1791

Confusion Matrix:
[[622 252]
 [577 340]]
